name: Create Release

on:
  push

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "version=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Generate release changelog
        id: generate_release_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: true
        with:
          # commitMode: true
          # fetchViaCommits: true
          configurationJson: |
            {
                "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
                "categories": [
                    {
                        "title": "## 🚀 Features",
                        "labels": [
                            "[feat]",
                            "[feature]",
                            "[Feature]"
                        ]
                    },
                    {
                        "title": "## 🐛 Fixes",
                        "labels": [
                            "[fix]",
                            "[bug]",
                            "[Fix]"
                        ]
                    },
                    {
                        "title": "## 🛠️ Chores",
                        "labels": [
                            "[chore]",
                            "[Chore]"
                        ]
                    },
                    {
                        "title": "## 🛠️ Dependencies",
                        "labels": [
                            "[deps]"
                        ]
                    }
                ],
                "label_extractor": [
                    {
                        "method": "match",
                        "pattern": "\\[.+?\\]",
                        "on_property": "title"
                    }
                ]
            }

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: ${{ steps.generate_release_changelog.outputs.changelog }}
          draft: false
          prerelease: false